In [1]:

import numpy as np
import pandas as pd 
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/celeb-df-v2/List_of_testing_videos.txt
/kaggle/input/celeb-df-v2/YouTube-real/00238.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00152.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00269.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00209.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00297.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00096.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00255.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00230.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00259.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00012.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00219.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00003.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00147.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00241.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00260.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00128.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00243.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00248.mp4
/kaggle/input/celeb-df-v2/YouTube-real/00207.mp4
/kaggle/input/ce

In [2]:
import os
import cv2
import random
import shutil
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, models
import glob

In [3]:
pip install torch torchvision timm numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
dataset_path = '/kaggle/input/celeb-df-v2'
real_videos_path = os.path.join(dataset_path, 'Celeb-real')
fake_videos_path = os.path.join(dataset_path, 'Celeb-synthesis')

print(f"real samples: {len(os.listdir(os.path.join(dataset_path, real_videos_path)))}")
print(f"fake samples: {len(os.listdir(os.path.join(dataset_path, fake_videos_path)))}")

real samples: 590
fake samples: 5639


In [5]:
SPLIT_OUTPUT_DIR = "/kaggle/working/split_videos"

REAL_TRAIN_DIR = os.path.join(SPLIT_OUTPUT_DIR, "REAL/train")
REAL_VAL_DIR = os.path.join(SPLIT_OUTPUT_DIR, "REAL/val")
REAL_TEST_DIR = os.path.join(SPLIT_OUTPUT_DIR, "REAL/test")

FAKE_TRAIN_DIR = os.path.join(SPLIT_OUTPUT_DIR, "Fake/train")
FAKE_VAL_DIR = os.path.join(SPLIT_OUTPUT_DIR, "Fake/val")
FAKE_TEST_DIR = os.path.join(SPLIT_OUTPUT_DIR, "Fake/test")

def split_and_balance_videos(source_dir, train_dir, val_dir, test_dir, train_ratio=0.7, val_ratio=0.1, balance_ratio=None):
    
    # Read videos from the source directory
    videos = [os.path.join(source_dir, video) for video in os.listdir(source_dir) if video.endswith(('.mp4', '.avi', '.mov'))]
    
    if not videos:
        print(f"No videos found in {source_dir}")
        return

    # Apply balance if balance_ratio is set
    if balance_ratio is not None:
        videos = train_test_split(videos, test_size=balance_ratio, random_state=42)[1]

    # Split videos into train and remaining sets
    train_videos, remaining_videos = train_test_split(videos, test_size=(1 - train_ratio), random_state=42)
    
    # Split remaining videos into validation and test sets
    val_ratio_adjusted = val_ratio / (1 - train_ratio)  # Adjusted validation ratio
    val_videos, test_videos = train_test_split(remaining_videos, test_size=(1 - val_ratio_adjusted), random_state=42)

    # Copy videos to respective directories
    for video_set, output_dir in zip([train_videos, val_videos, test_videos], [train_dir, val_dir, test_dir]):
        os.makedirs(output_dir, exist_ok=True)
        for video_path in video_set:
            shutil.copy(video_path, output_dir)

    print(f"Splitting completed for {source_dir}:")
    print(f"  Train: {len(train_videos)} videos -> {train_dir}")
    print(f"  Validation: {len(val_videos)} videos -> {val_dir}")
    print(f"  Test: {len(test_videos)} videos -> {test_dir}")


In [6]:
split_and_balance_videos(real_videos_path, REAL_TRAIN_DIR, REAL_VAL_DIR, REAL_TEST_DIR)

split_and_balance_videos(fake_videos_path, FAKE_TRAIN_DIR, FAKE_VAL_DIR, FAKE_TEST_DIR, balance_ratio=0.11)


Splitting completed for /kaggle/input/celeb-df-v2/Celeb-real:
  Train: 412 videos -> /kaggle/working/split_videos/REAL/train
  Validation: 59 videos -> /kaggle/working/split_videos/REAL/val
  Test: 119 videos -> /kaggle/working/split_videos/REAL/test
Splitting completed for /kaggle/input/celeb-df-v2/Celeb-synthesis:
  Train: 434 videos -> /kaggle/working/split_videos/Fake/train
  Validation: 62 videos -> /kaggle/working/split_videos/Fake/val
  Test: 125 videos -> /kaggle/working/split_videos/Fake/test


In [7]:
import os
import cv2

def extract_frames(source_dir, output_dir, frame_rate=30):
    
    print(f"Processing videos in: {source_dir}")
    os.makedirs(output_dir, exist_ok=True)

    video_files = [f for f in os.listdir(source_dir) if f.endswith(('.mp4', '.avi', '.mov'))]
    if not video_files:
        print(f"No video files found in {source_dir}.")
        return

    for video_file in video_files:
        video_path = os.path.join(source_dir, video_file)

        # Create a subdirectory for the video's frames
        video_frames_dir = os.path.join(output_dir, os.path.splitext(video_file)[0])
        os.makedirs(video_frames_dir, exist_ok=True)

        # Extract frames from the video
        cap = cv2.VideoCapture(video_path)
        frame_count = 0
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            if int(cap.get(cv2.CAP_PROP_POS_FRAMES)) % frame_rate == 0:
                frame_path = os.path.join(video_frames_dir, f"frame_{frame_count}.jpg")
                cv2.imwrite(frame_path, frame)  # Save frame as an image
                frame_count += 1
        cap.release()
        print(f"Frames extracted for video: {video_file}")
    print(f"Frame extraction completed for: {source_dir}")

# Correct paths for validation directories
REAL_VAL_DIR = "/kaggle/working/split_videos/REAL/val"
FAKE_VAL_DIR = "/kaggle/working/split_videos/Fake/val"

# Output directory for extracted frames
OUTPUT_FRAMES_DIR = "/kaggle/working/extracted_frames/val"

# Extract frames for REAL and Fake validation videos
extract_frames(REAL_VAL_DIR, os.path.join(OUTPUT_FRAMES_DIR, "REAL"))
extract_frames(FAKE_VAL_DIR, os.path.join(OUTPUT_FRAMES_DIR, "Fake"))


Processing videos in: /kaggle/working/split_videos/REAL/val
Frames extracted for video: id19_0005.mp4
Frames extracted for video: id3_0007.mp4
Frames extracted for video: id7_0007.mp4
Frames extracted for video: id37_0007.mp4
Frames extracted for video: id61_0001.mp4
Frames extracted for video: id57_0000.mp4
Frames extracted for video: id53_0003.mp4
Frames extracted for video: id7_0003.mp4
Frames extracted for video: id22_0003.mp4
Frames extracted for video: id30_0006.mp4
Frames extracted for video: id56_0004.mp4
Frames extracted for video: id37_0005.mp4
Frames extracted for video: id50_0002.mp4
Frames extracted for video: id47_0009.mp4
Frames extracted for video: id45_0008.mp4
Frames extracted for video: id58_0007.mp4
Frames extracted for video: id11_0008.mp4
Frames extracted for video: id27_0003.mp4
Frames extracted for video: id13_0006.mp4
Frames extracted for video: id17_0004.mp4
Frames extracted for video: id8_0002.mp4
Frames extracted for video: id3_0008.mp4
Frames extracted for 

In [8]:
# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Set random seeds for reproducibility
def set_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)

set_seed(42)

# Define transformations
transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224, 224)),  # Adjust the size if needed
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # ImageNet mean
                         std=[0.229, 0.224, 0.225])    # ImageNet std
])

Using device: cuda


In [9]:
# Custom Dataset Class
class CustomDataset(Dataset):
    def __init__(self, file_paths, labels, transform=None):
        self.file_paths = file_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        image_path = self.file_paths[idx]
        image = cv2.imread(image_path)
    
        # Check if the image was loaded successfully
        if image is None:
            raise ValueError(f"Failed to load image: {image_path}")
        
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if self.transform:
            image = self.transform(image)
        label = self.labels[idx]
        return image, label

In [10]:
# Function to evaluate the model
def evaluate(model, loader):
    model.eval()
    all_labels, all_preds = [], []

    with torch.no_grad():
        for inputs, labels in loader:
            inputs = inputs.to(device)
            labels = labels.float().to(device)

            outputs = model(inputs).squeeze()
            probs = torch.sigmoid(outputs)
            preds = (probs > 0.5).float()

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())

    # Calculate metrics
    precision = precision_score(all_labels, all_preds, zero_division=0)
    recall = recall_score(all_labels, all_preds, zero_division=0)
    f1 = f1_score(all_labels, all_preds, zero_division=0)
    conf_matrix = confusion_matrix(all_labels, all_preds)
    accuracy = accuracy_score(all_labels, all_preds)
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print(f"Confusion Matrix:\n{conf_matrix}")
    return {'accuracy': accuracy, 'precision': precision, 'recall': recall, 'f1_score': f1}


In [11]:
# Function for simulated annealing to find the best learning rate
def simulated_annealing_lr(model, criterion, dataloader, upper_lr=0.001, epochs=5):
    best_lr = upper_lr
    best_loss = float('inf')
    current_lr = random.uniform(1e-5, upper_lr)

    for epoch in range(epochs):
        optimizer = optim.SGD(filter(lambda p: p.requires_grad, model.parameters()), lr=current_lr)
        model.train()
        total_loss = 0

        for images, labels in dataloader:
            images = images.to(device)
            labels = labels.float().to(device)

            optimizer.zero_grad()
            outputs = model(images).squeeze()
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        avg_loss = total_loss / len(dataloader)
        if avg_loss < best_loss:
            best_loss = avg_loss
            best_lr = current_lr

        current_lr *= 0.9  # Decrease learning rate
        print(f"Iteration {epoch+1} ---------- Best LR = {best_lr} ---------- Loss = {best_loss}")

    return best_lr


In [12]:
# Function to create and configure the model
def create_model(model_name, num_classes=1, fine_tune=False, unfreeze_layers=2, add_extra_conv=False):
    if model_name == "vgg16":
        model = models.vgg16(pretrained=True)
        if fine_tune:
       
            for param in model.parameters():
                param.requires_grad = False
           
            for param in model.features[-(unfreeze_layers*2):].parameters():
                param.requires_grad = True
        if add_extra_conv:
          
            model.features.add_module("extra_conv", nn.Conv2d(512, 512, kernel_size=3, padding=1))
            model.features.add_module("extra_relu", nn.ReLU(inplace=True))

        num_features = model.classifier[-1].in_features
        model.classifier[-1] = nn.Linear(num_features, num_classes)

    elif model_name == "resnet50":
        model = models.resnet50(pretrained=True)
        if fine_tune:
          
            for param in model.parameters():
                param.requires_grad = False
         
            layers = list(model.children())[:-1]
            for layer in layers[-unfreeze_layers:]:
                for param in layer.parameters():
                    param.requires_grad = True
        if add_extra_conv:
           
            model.layer4.add_module("extra_conv", nn.Conv2d(2048, 2048, kernel_size=3, padding=1))
            model.layer4.add_module("extra_relu", nn.ReLU(inplace=True))

        num_features = model.fc.in_features
        model.fc = nn.Linear(num_features, num_classes)

    elif model_name == "densenet121":
        model = models.densenet121(pretrained=True)
        if fine_tune:
         
            for param in model.parameters():
                param.requires_grad = False
          
            for param in model.features.denseblock4.parameters():
                param.requires_grad = True
        if add_extra_conv:
        
            model.features.add_module("extra_conv", nn.Conv2d(1024, 1024, kernel_size=3, padding=1))
            model.features.add_module("extra_relu", nn.ReLU(inplace=True))

        num_features = model.classifier.in_features
        model.classifier = nn.Linear(num_features, num_classes)

    elif model_name == "mobilenet_v2":
        model = models.mobilenet_v2(pretrained=True)
        if fine_tune:
        
            for param in model.parameters():
                param.requires_grad = False
        
            for param in model.features[-(unfreeze_layers):].parameters():
                param.requires_grad = True
        if add_extra_conv:
       
            model.features.add_module("extra_conv", nn.Conv2d(1280, 1280, kernel_size=3, padding=1))
            model.features.add_module("extra_relu", nn.ReLU(inplace=True))

        num_features = model.last_channel
        model.classifier[1] = nn.Linear(num_features, num_classes)

    elif model_name == "inception_v3":
        model = models.inception_v3(pretrained=True, aux_logits=False)
        if fine_tune:
            # Freeze all layers
            for param in model.parameters():
                param.requires_grad = False
            # Unfreeze the last convolutional layers
            for param in model.Mixed_7c.parameters():
                param.requires_grad = True
            if unfreeze_layers > 1:
                for param in model.Mixed_7b.parameters():
                    param.requires_grad = True
        if add_extra_conv:
            # Add an extra convolutional layer
            model.Mixed_7c.add_module("extra_conv", nn.Conv2d(2048, 2048, kernel_size=3, padding=1))
            model.Mixed_7c.add_module("extra_relu", nn.ReLU(inplace=True))

        num_features = model.fc.in_features
        model.fc = nn.Linear(num_features, num_classes)

    elif model_name == "vision_transformer":
        # Import timm and create vision transformer model
        import timm
        model = timm.create_model('vit_base_patch16_224', pretrained=True)
        if fine_tune:
            # Freeze all layers
            for param in model.parameters():
                param.requires_grad = False
            # Unfreeze the last transformer blocks
            for param in model.blocks[-unfreeze_layers:].parameters():
                param.requires_grad = True
        num_features = model.head.in_features
        model.head = nn.Linear(num_features, num_classes)
        
    else:
        raise ValueError(f"Unsupported model: {model_name}")
    return model


In [ ]:
def k_fold_cross_validation(k, model_name, dataset, batch_size=32, epochs=5, fine_tune=False, unfreeze_layers=2, add_extra_conv=False):
    kf = KFold(n_splits=k, shuffle=True, random_state=42)
    fold_metrics = []
    fold = 0

    for train_idx, test_idx in kf.split(dataset):
        fold +=1
        print(f"\nStarting Fold {fold}")

        train_subset = torch.utils.data.Subset(dataset, train_idx)
        test_subset = torch.utils.data.Subset(dataset, test_idx)

        # Create DataLoaders from the subsets
        train_loader = DataLoader(train_subset, batch_size=batch_size, shuffle=True)
        test_loader = DataLoader(test_subset, batch_size=batch_size, shuffle=False)

        model = create_model(model_name, fine_tune=fine_tune, unfreeze_layers=unfreeze_layers, add_extra_conv=add_extra_conv)
        model = model.to(device)

        criterion = nn.BCEWithLogitsLoss()

        best_lr = simulated_annealing_lr(model, criterion, train_loader)
        optimizer = optim.SGD(filter(lambda p: p.requires_grad, model.parameters()), lr=best_lr, momentum=0.9)

        # Training loop
        for epoch in range(epochs):
            model.train()
            total_loss = 0
            for images, labels in train_loader:
                images = images.to(device)
                labels = labels.float().to(device)  # Convert labels to float

                optimizer.zero_grad()
                outputs = model(images).squeeze()
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                total_loss += loss.item()

            avg_loss = total_loss / len(train_loader)
            print(f"Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.4f}")

        # Evaluate the model
        metrics = evaluate(model, test_loader)
        fold_metrics.append(metrics)

    # Calculate average metrics
    avg_accuracy = np.mean([m['accuracy'] for m in fold_metrics])
    avg_precision = np.mean([m['precision'] for m in fold_metrics])
    avg_recall = np.mean([m['recall'] for m in fold_metrics])
    avg_f1 = np.mean([m['f1_score'] for m in fold_metrics])
    print(f"\nAverage Metrics for {model_name}:")
    print(f"Accuracy: {avg_accuracy:.4f}")
    print(f"Precision: {avg_precision:.4f}")
    print(f"Recall: {avg_recall:.4f}")
    print(f"F1 Score: {avg_f1:.4f}")

    # Return the last trained model and metrics
    return model, {'accuracy': avg_accuracy, 'precision': avg_precision, 'recall': avg_recall, 'f1_score': avg_f1}



In [14]:
def run_experiments():
    import traceback  # For detailed error logs
    import pickle     # For saving results to files

  
    TRAIN_DIR = "/kaggle/working/extracted_frames/val"

   
    real_image_paths = glob.glob(os.path.join(TRAIN_DIR, "REAL", "**", "*.jpg"), recursive=True)
    fake_image_paths = glob.glob(os.path.join(TRAIN_DIR, "Fake", "**", "*.jpg"), recursive=True)

    all_files = real_image_paths + fake_image_paths
    all_labels = [0] * len(real_image_paths) + [1] * len(fake_image_paths)  # 0 for REAL, 1 for Fake

   
    dataset = CustomDataset(all_files, all_labels, transform=transform)

    # Models to experiment with
    model_names = ["resnet50", "vgg16", "mobilenet_v2", "densenet121", "inception_v3", "vision_transformer"]
    results = {}
    errors = {}

    for model_name in model_names:
        print(f"\nRunning experiments for model: {model_name}")

        try:
            # Base Model
            print("\n--- Base Model ---")
            base_model, base_metrics = k_fold_cross_validation(
                k=3,
                model_name=model_name,
                dataset=dataset,
                epochs=5,
                fine_tune=False,
                unfreeze_layers=0,
                add_extra_conv=False
            )
            results[f"{model_name}_base"] = base_metrics

            # Save results after each experiment
            with open('results.pkl', 'wb') as f:
                pickle.dump(results, f)

            # Fine-tuned Model
            print("\n--- Fine-tuned Model ---")
            fine_tuned_model, fine_tuned_metrics = k_fold_cross_validation(
                k=3,
                model_name=model_name,
                dataset=dataset,
                epochs=5,
                fine_tune=True,
                unfreeze_layers=2,  # Fine-tune last 2 layers
                add_extra_conv=False
            )
            results[f"{model_name}_fine_tuned"] = fine_tuned_metrics

            # Save results
            with open('results.pkl', 'wb') as f:
                pickle.dump(results, f)

            # Model with Extra Convolutional Layer
            print("\n--- Model with Extra Convolutional Layer ---")
            extra_conv_model, extra_conv_metrics = k_fold_cross_validation(
                k=3,
                model_name=model_name,
                dataset=dataset,
                epochs=5,
                fine_tune=True,
                unfreeze_layers=2,
                add_extra_conv=True
            )
            results[f"{model_name}_extra_conv"] = extra_conv_metrics

            # Save results
            with open('results.pkl', 'wb') as f:
                pickle.dump(results, f)

        except Exception as e:
            print(f"\nAn error occurred while processing model {model_name}: {e}")
            # Capture the traceback
            error_details = traceback.format_exc()
            print(error_details)
            errors[model_name] = error_details
            # Continue to the next model

        # Optionally, clear CUDA cache to free up memory after each model
        torch.cuda.empty_cache()

    # Print results
    print("\n\n--- Summary of Results ---")
    for key, value in results.items():
        print(f"{key}: Accuracy={value['accuracy']:.4f}, Precision={value['precision']:.4f}, "
              f"Recall={value['recall']:.4f}, F1 Score={value['f1_score']:.4f}")

    # Save final results
    with open('final_results.pkl', 'wb') as f:
        pickle.dump(results, f)

    # Save errors if any
    if errors:
        with open('errors.pkl', 'wb') as f:
            pickle.dump(errors, f)
        print("\nErrors occurred in the following models:")
        for model_name, error_detail in errors.items():
            print(f"{model_name}:\n{error_detail}")

    # Find the best model
    if results:
        best_model_name = max(results, key=lambda k: results[k]['accuracy'])
        print(f"\nBest model is {best_model_name} with accuracy {results[best_model_name]['accuracy']:.4f}")
    else:
        print("No successful results to determine the best model.")

In [15]:
if __name__ == "__main__":
    run_experiments()


Running experiments for model: resnet50

--- Base Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|██████████| 97.8M/97.8M [00:00<00:00, 213MB/s]


Iteration 1 ---------- Best LR = 0.0006430325304733049 ---------- Loss = 0.7091847807168961
Iteration 2 ---------- Best LR = 0.0005787292774259744 ---------- Loss = 0.6934578660875559
Iteration 3 ---------- Best LR = 0.000520856349683377 ---------- Loss = 0.6820209342986345
Iteration 4 ---------- Best LR = 0.0004687707147150393 ---------- Loss = 0.6716282237321138
Iteration 5 ---------- Best LR = 0.0004218936432435354 ---------- Loss = 0.6604954302310944
Epoch [1/5], Loss: 0.6383
Epoch [2/5], Loss: 0.5598
Epoch [3/5], Loss: 0.4634
Epoch [4/5], Loss: 0.3628
Epoch [5/5], Loss: 0.2719
Accuracy: 0.9542
Precision: 0.9466
Recall: 0.9650
F1 Score: 0.9557
Confusion Matrix:
[[231  14]
 [  9 248]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 3.476064767044027e-05 ---------- Loss = 0.6977375708520412
Iteration 2 ---------- Best LR = 3.128458290339624e-05 ---------- Loss = 0.6974752601236105
Iteration 3 ---------- Best LR = 2.8156124613056618e-05 ---------- Loss = 0.6954411715269089
Iteration 4 ---------- Best LR = 2.5340512151750955e-05 ---------- Loss = 0.6950948499143124
Iteration 5 ---------- Best LR = 2.280646093657586e-05 ---------- Loss = 0.6936644054949284
Epoch [1/5], Loss: 0.6917
Epoch [2/5], Loss: 0.6884
Epoch [3/5], Loss: 0.6842
Epoch [4/5], Loss: 0.6783
Epoch [5/5], Loss: 0.6725
Accuracy: 0.5558
Precision: 0.5223
Recall: 0.7395
F1 Score: 0.6122
Confusion Matrix:
[[103 161]
 [ 62 176]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0002822790251854281 ---------- Loss = 0.6822364013642073
Iteration 2 ---------- Best LR = 0.0002540511226668853 ---------- Loss = 0.6755710709840059
Iteration 3 ---------- Best LR = 0.00022864601040019678 ---------- Loss = 0.671447891741991
Iteration 4 ---------- Best LR = 0.00020578140936017712 ---------- Loss = 0.6678499486297369
Iteration 5 ---------- Best LR = 0.00018520326842415941 ---------- Loss = 0.6634418740868568
Epoch [1/5], Loss: 0.6556
Epoch [2/5], Loss: 0.6248
Epoch [3/5], Loss: 0.5889
Epoch [4/5], Loss: 0.5484
Epoch [5/5], Loss: 0.5056
Accuracy: 0.8884
Precision: 0.9197
Recall: 0.8642
F1 Score: 0.8911
Confusion Matrix:
[[217  20]
 [ 36 229]]

Average Metrics for resnet50:
Accuracy: 0.7995
Precision: 0.7962
Recall: 0.8562
F1 Score: 0.8196

--- Fine-tuned Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00023097863076733453 ---------- Loss = 0.6900443229824305
Iteration 2 ---------- Best LR = 0.00020788076769060108 ---------- Loss = 0.6817690040916204
Iteration 3 ---------- Best LR = 0.00018709269092154099 ---------- Loss = 0.6807819195091724
Iteration 4 ---------- Best LR = 0.00016838342182938688 ---------- Loss = 0.6762723308056593
Iteration 5 ---------- Best LR = 0.0001515450796464482 ---------- Loss = 0.6731582563370466
Epoch [1/5], Loss: 0.6659
Epoch [2/5], Loss: 0.6416
Epoch [3/5], Loss: 0.6188
Epoch [4/5], Loss: 0.5951
Epoch [5/5], Loss: 0.5658
Accuracy: 0.8028
Precision: 0.7669
Recall: 0.8833
F1 Score: 0.8210
Confusion Matrix:
[[176  69]
 [ 30 227]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0007391065020223722 ---------- Loss = 0.6856247372925282
Iteration 2 ---------- Best LR = 0.0006651958518201351 ---------- Loss = 0.6747619193047285
Iteration 3 ---------- Best LR = 0.0005986762666381215 ---------- Loss = 0.6644933857023716
Iteration 4 ---------- Best LR = 0.0005388086399743094 ---------- Loss = 0.6576380077749491
Iteration 5 ---------- Best LR = 0.0004849277759768785 ---------- Loss = 0.647758349776268
Epoch [1/5], Loss: 0.6268
Epoch [2/5], Loss: 0.5589
Epoch [3/5], Loss: 0.4820
Epoch [4/5], Loss: 0.3830
Epoch [5/5], Loss: 0.3092
Accuracy: 0.9084
Precision: 0.8721
Recall: 0.9454
F1 Score: 0.9073
Confusion Matrix:
[[231  33]
 [ 13 225]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0006799324925486822 ---------- Loss = 0.6949976533651352
Iteration 2 ---------- Best LR = 0.0006119392432938141 ---------- Loss = 0.6830134019255638
Iteration 3 ---------- Best LR = 0.0005507453189644327 ---------- Loss = 0.6753664165735245
Iteration 4 ---------- Best LR = 0.0004956707870679895 ---------- Loss = 0.6660862267017365
Iteration 5 ---------- Best LR = 0.00044610370836119055 ---------- Loss = 0.659813953563571
Epoch [1/5], Loss: 0.6409
Epoch [2/5], Loss: 0.5851
Epoch [3/5], Loss: 0.5220
Epoch [4/5], Loss: 0.4374
Epoch [5/5], Loss: 0.3596
Accuracy: 0.9343
Precision: 0.9427
Recall: 0.9321
F1 Score: 0.9374
Confusion Matrix:
[[222  15]
 [ 18 247]]

Average Metrics for resnet50:
Accuracy: 0.8818
Precision: 0.8606
Recall: 0.9202
F1 Score: 0.8885

--- Model with Extra Convolutional Layer ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.000893257772027797 ---------- Loss = 0.6909091249108315
Iteration 2 ---------- Best LR = 0.0008039319948250173 ---------- Loss = 0.6814643647521734
Iteration 3 ---------- Best LR = 0.0007235387953425156 ---------- Loss = 0.673466868698597
Iteration 4 ---------- Best LR = 0.000651184915808264 ---------- Loss = 0.6669019870460033
Iteration 5 ---------- Best LR = 0.0005860664242274377 ---------- Loss = 0.6600688323378563
Epoch [1/5], Loss: 0.6411
Epoch [2/5], Loss: 0.5691
Epoch [3/5], Loss: 0.4608
Epoch [4/5], Loss: 0.3534
Epoch [5/5], Loss: 0.2424
Accuracy: 0.9183
Precision: 0.9821
Recall: 0.8560
F1 Score: 0.9148
Confusion Matrix:
[[241   4]
 [ 37 220]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 9.6069444303122e-05 ---------- Loss = 0.695934584364295
Iteration 2 ---------- Best LR = 8.64624998728098e-05 ---------- Loss = 0.6925187073647976
Iteration 3 ---------- Best LR = 7.781624988552882e-05 ---------- Loss = 0.6916891429573298
Iteration 4 ---------- Best LR = 7.781624988552882e-05 ---------- Loss = 0.6916891429573298
Iteration 5 ---------- Best LR = 6.303116240727834e-05 ---------- Loss = 0.6898058131337166
Epoch [1/5], Loss: 0.6887
Epoch [2/5], Loss: 0.6814
Epoch [3/5], Loss: 0.6756
Epoch [4/5], Loss: 0.6682
Epoch [5/5], Loss: 0.6620
Accuracy: 0.6952
Precision: 0.6218
Recall: 0.9118
F1 Score: 0.7394
Confusion Matrix:
[[132 132]
 [ 21 217]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00042770260148841774 ---------- Loss = 0.6936459913849831
Iteration 2 ---------- Best LR = 0.00038493234133957596 ---------- Loss = 0.6883114725351334
Iteration 3 ---------- Best LR = 0.0003464391072056184 ---------- Loss = 0.6848206501454115
Iteration 4 ---------- Best LR = 0.00031179519648505654 ---------- Loss = 0.6813373677432537
Iteration 5 ---------- Best LR = 0.0002806156768365509 ---------- Loss = 0.6784823760390282
Epoch [1/5], Loss: 0.6727
Epoch [2/5], Loss: 0.6474
Epoch [3/5], Loss: 0.6184
Epoch [4/5], Loss: 0.5795
Epoch [5/5], Loss: 0.5364
Accuracy: 0.8745
Precision: 0.8367
Recall: 0.9472
F1 Score: 0.8885
Confusion Matrix:
[[188  49]
 [ 14 251]]

Average Metrics for resnet50:
Accuracy: 0.8293
Precision: 0.8135
Recall: 0.9050
F1 Score: 0.8475

Running experiments for model: vgg16

--- Base Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100%|██████████| 528M/528M [00:02<00:00, 237MB/s]


Iteration 1 ---------- Best LR = 3.949924724368964e-05 ---------- Loss = 0.7341738510876894
Iteration 2 ---------- Best LR = 3.554932251932068e-05 ---------- Loss = 0.7237428445369005
Iteration 3 ---------- Best LR = 3.1994390267388616e-05 ---------- Loss = 0.7073265984654427
Iteration 4 ---------- Best LR = 3.1994390267388616e-05 ---------- Loss = 0.7073265984654427
Iteration 5 ---------- Best LR = 3.1994390267388616e-05 ---------- Loss = 0.7073265984654427
Epoch [1/5], Loss: 0.7035
Epoch [2/5], Loss: 0.6863
Epoch [3/5], Loss: 0.6779
Epoch [4/5], Loss: 0.6701
Epoch [5/5], Loss: 0.6548
Accuracy: 0.6912
Precision: 0.6848
Recall: 0.7354
F1 Score: 0.7092
Confusion Matrix:
[[158  87]
 [ 68 189]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00022645159505556734 ---------- Loss = 0.7117149531841278
Iteration 2 ---------- Best LR = 0.00020380643555001062 ---------- Loss = 0.6896107979118824
Iteration 3 ---------- Best LR = 0.00018342579199500956 ---------- Loss = 0.6863953806459904
Iteration 4 ---------- Best LR = 0.0001650832127955086 ---------- Loss = 0.6790156457573175
Iteration 5 ---------- Best LR = 0.00014857489151595774 ---------- Loss = 0.6716890912503004
Epoch [1/5], Loss: 0.6546
Epoch [2/5], Loss: 0.6019
Epoch [3/5], Loss: 0.5384
Epoch [4/5], Loss: 0.4917
Epoch [5/5], Loss: 0.4317
Accuracy: 0.7849
Precision: 0.7642
Recall: 0.7899
F1 Score: 0.7769
Confusion Matrix:
[[206  58]
 [ 50 188]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0005103017352223288 ---------- Loss = 0.7077048178762197
Iteration 2 ---------- Best LR = 0.0004592715617000959 ---------- Loss = 0.6887397114187479
Iteration 3 ---------- Best LR = 0.00041334440553008635 ---------- Loss = 0.6701339893043041
Iteration 4 ---------- Best LR = 0.0003720099649770777 ---------- Loss = 0.6514425557106733
Iteration 5 ---------- Best LR = 0.00033480896847936997 ---------- Loss = 0.6399923209100962
Epoch [1/5], Loss: 0.6180
Epoch [2/5], Loss: 0.5212
Epoch [3/5], Loss: 0.3860
Epoch [4/5], Loss: 0.2850
Epoch [5/5], Loss: 0.1966
Accuracy: 0.9223
Precision: 0.9094
Recall: 0.9472
F1 Score: 0.9279
Confusion Matrix:
[[212  25]
 [ 14 251]]

Average Metrics for vgg16:
Accuracy: 0.7995
Precision: 0.7861
Recall: 0.8242
F1 Score: 0.8047

--- Fine-tuned Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 3.627060998702499e-05 ---------- Loss = 0.7263456303626299
Iteration 2 ---------- Best LR = 3.264354898832249e-05 ---------- Loss = 0.7243383955210447
Iteration 3 ---------- Best LR = 2.9379194089490246e-05 ---------- Loss = 0.7190958615392447
Iteration 4 ---------- Best LR = 2.644127468054122e-05 ---------- Loss = 0.7162737902253866
Iteration 5 ---------- Best LR = 2.644127468054122e-05 ---------- Loss = 0.7162737902253866
Epoch [1/5], Loss: 0.7140
Epoch [2/5], Loss: 0.7023
Epoch [3/5], Loss: 0.7023
Epoch [4/5], Loss: 0.6871
Epoch [5/5], Loss: 0.6849
Accuracy: 0.6295
Precision: 0.6340
Recall: 0.6537
F1 Score: 0.6437
Confusion Matrix:
[[148  97]
 [ 89 168]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.000206849274179782 ---------- Loss = 0.6994301527738571
Iteration 2 ---------- Best LR = 0.00018616434676180382 ---------- Loss = 0.690291415899992
Iteration 3 ---------- Best LR = 0.00016754791208562343 ---------- Loss = 0.6874376367777586
Iteration 4 ---------- Best LR = 0.0001507931208770611 ---------- Loss = 0.6776175461709499
Iteration 5 ---------- Best LR = 0.000135713808789355 ---------- Loss = 0.6666391640901566
Epoch [1/5], Loss: 0.6635
Epoch [2/5], Loss: 0.6407
Epoch [3/5], Loss: 0.6111
Epoch [4/5], Loss: 0.5912
Epoch [5/5], Loss: 0.5667
Accuracy: 0.7191
Precision: 0.6803
Recall: 0.7689
F1 Score: 0.7219
Confusion Matrix:
[[178  86]
 [ 55 183]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.000653385593401728 ---------- Loss = 0.7019838895648718
Iteration 2 ---------- Best LR = 0.0005880470340615552 ---------- Loss = 0.6903009321540594
Iteration 3 ---------- Best LR = 0.0005292423306553997 ---------- Loss = 0.6737070512026548
Iteration 4 ---------- Best LR = 0.0004763180975898598 ---------- Loss = 0.6572279334068298
Iteration 5 ---------- Best LR = 0.00042868628783087384 ---------- Loss = 0.6544118151068687
Epoch [1/5], Loss: 0.6362
Epoch [2/5], Loss: 0.5969
Epoch [3/5], Loss: 0.5370
Epoch [4/5], Loss: 0.5163
Epoch [5/5], Loss: 0.4797
Accuracy: 0.8506
Precision: 0.8417
Recall: 0.8830
F1 Score: 0.8619
Confusion Matrix:
[[193  44]
 [ 31 234]]

Average Metrics for vgg16:
Accuracy: 0.7331
Precision: 0.7187
Recall: 0.7685
F1 Score: 0.7425

--- Model with Extra Convolutional Layer ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0005494920657971845 ---------- Loss = 0.6949159875512123
Iteration 2 ---------- Best LR = 0.0004945428592174661 ---------- Loss = 0.692012021318078
Iteration 3 ---------- Best LR = 0.0004945428592174661 ---------- Loss = 0.692012021318078
Iteration 4 ---------- Best LR = 0.0004945428592174661 ---------- Loss = 0.692012021318078
Iteration 5 ---------- Best LR = 0.0003605217443695328 ---------- Loss = 0.6915693338960409
Epoch [1/5], Loss: 0.6931
Epoch [2/5], Loss: 0.6923
Epoch [3/5], Loss: 0.6904
Epoch [4/5], Loss: 0.6916
Epoch [5/5], Loss: 0.6883
Accuracy: 0.6235
Precision: 0.6453
Recall: 0.5875
F1 Score: 0.6151
Confusion Matrix:
[[162  83]
 [106 151]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00022823621582028974 ---------- Loss = 0.6936035752296448
Iteration 2 ---------- Best LR = 0.00022823621582028974 ---------- Loss = 0.6936035752296448
Iteration 3 ---------- Best LR = 0.0001848713348144347 ---------- Loss = 0.6930390670895576
Iteration 4 ---------- Best LR = 0.0001848713348144347 ---------- Loss = 0.6930390670895576
Iteration 5 ---------- Best LR = 0.00014974578119969213 ---------- Loss = 0.6923966184258461
Epoch [1/5], Loss: 0.6933
Epoch [2/5], Loss: 0.6935
Epoch [3/5], Loss: 0.6914
Epoch [4/5], Loss: 0.6927
Epoch [5/5], Loss: 0.6913
Accuracy: 0.4741
Precision: 0.4741
Recall: 1.0000
F1 Score: 0.6432
Confusion Matrix:
[[  0 264]
 [  0 238]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0005933730270371497 ---------- Loss = 0.6917801070958376
Iteration 2 ---------- Best LR = 0.0005933730270371497 ---------- Loss = 0.6917801070958376
Iteration 3 ---------- Best LR = 0.0005933730270371497 ---------- Loss = 0.6917801070958376
Iteration 4 ---------- Best LR = 0.0005933730270371497 ---------- Loss = 0.6917801070958376
Iteration 5 ---------- Best LR = 0.0005933730270371497 ---------- Loss = 0.6917801070958376
Epoch [1/5], Loss: 0.6915
Epoch [2/5], Loss: 0.6905
Epoch [3/5], Loss: 0.6882
Epoch [4/5], Loss: 0.6867
Epoch [5/5], Loss: 0.6855
Accuracy: 0.7351
Precision: 0.7640
Recall: 0.7208
F1 Score: 0.7417
Confusion Matrix:
[[178  59]
 [ 74 191]]

Average Metrics for vgg16:
Accuracy: 0.6109
Precision: 0.6278
Recall: 0.7694
F1 Score: 0.6667

Running experiments for model: mobilenet_v2

--- Base Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /root/.cache/torch/hub/checkpoints/mobilenet_v2-b0353104.pth
100%|██████████| 13.6M/13.6M [00:00<00:00, 111MB/s] 


Iteration 1 ---------- Best LR = 0.0008113361521110484 ---------- Loss = 0.6826157700270414
Iteration 2 ---------- Best LR = 0.0007302025368999436 ---------- Loss = 0.6553112100809813
Iteration 3 ---------- Best LR = 0.0006571822832099492 ---------- Loss = 0.6344587728381157
Iteration 4 ---------- Best LR = 0.0005914640548889543 ---------- Loss = 0.6242167316377163
Iteration 5 ---------- Best LR = 0.0005323176494000588 ---------- Loss = 0.6106226313859224
Epoch [1/5], Loss: 0.5794
Epoch [2/5], Loss: 0.4582
Epoch [3/5], Loss: 0.3448
Epoch [4/5], Loss: 0.2389
Epoch [5/5], Loss: 0.1622
Accuracy: 0.9283
Precision: 0.9333
Recall: 0.9261
F1 Score: 0.9297
Confusion Matrix:
[[228  17]
 [ 19 238]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 1.643377208128041e-05 ---------- Loss = 0.6985094714909792
Iteration 2 ---------- Best LR = 1.643377208128041e-05 ---------- Loss = 0.6985094714909792
Iteration 3 ---------- Best LR = 1.643377208128041e-05 ---------- Loss = 0.6985094714909792
Iteration 4 ---------- Best LR = 1.643377208128041e-05 ---------- Loss = 0.6985094714909792
Iteration 5 ---------- Best LR = 1.643377208128041e-05 ---------- Loss = 0.6985094714909792
Epoch [1/5], Loss: 0.6991
Epoch [2/5], Loss: 0.6956
Epoch [3/5], Loss: 0.6939
Epoch [4/5], Loss: 0.6880
Epoch [5/5], Loss: 0.6811
Accuracy: 0.5239
Precision: 0.4985
Recall: 0.7059
F1 Score: 0.5843
Confusion Matrix:
[[ 95 169]
 [ 70 168]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0008077610593144798 ---------- Loss = 0.6926061455160379
Iteration 2 ---------- Best LR = 0.0007269849533830319 ---------- Loss = 0.6729302071034908
Iteration 3 ---------- Best LR = 0.0006542864580447287 ---------- Loss = 0.6510904058814049
Iteration 4 ---------- Best LR = 0.0005888578122402559 ---------- Loss = 0.6427167505025864
Iteration 5 ---------- Best LR = 0.0005299720310162304 ---------- Loss = 0.6295556519180536
Epoch [1/5], Loss: 0.6070
Epoch [2/5], Loss: 0.4892
Epoch [3/5], Loss: 0.3617
Epoch [4/5], Loss: 0.2471
Epoch [5/5], Loss: 0.1711
Accuracy: 0.9542
Precision: 0.9449
Recall: 0.9698
F1 Score: 0.9572
Confusion Matrix:
[[222  15]
 [  8 257]]

Average Metrics for mobilenet_v2:
Accuracy: 0.8021
Precision: 0.7922
Recall: 0.8673
F1 Score: 0.8237

--- Fine-tuned Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0007011580010383447 ---------- Loss = 0.6873843744397163
Iteration 2 ---------- Best LR = 0.0006310422009345102 ---------- Loss = 0.673991622403264
Iteration 3 ---------- Best LR = 0.0005679379808410592 ---------- Loss = 0.6688876207917929
Iteration 4 ---------- Best LR = 0.0005111441827569533 ---------- Loss = 0.6655580122023821
Iteration 5 ---------- Best LR = 0.00046002976448125796 ---------- Loss = 0.6584645602852106
Epoch [1/5], Loss: 0.6296
Epoch [2/5], Loss: 0.5875
Epoch [3/5], Loss: 0.5353
Epoch [4/5], Loss: 0.4919
Epoch [5/5], Loss: 0.4515
Accuracy: 0.8386
Precision: 0.8212
Recall: 0.8755
F1 Score: 0.8475
Confusion Matrix:
[[196  49]
 [ 32 225]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.000346848011352812 ---------- Loss = 0.6916941441595554
Iteration 2 ---------- Best LR = 0.000346848011352812 ---------- Loss = 0.6916941441595554
Iteration 3 ---------- Best LR = 0.00028094688919577774 ---------- Loss = 0.6805190201848745
Iteration 4 ---------- Best LR = 0.00025285220027619995 ---------- Loss = 0.6755058746784925
Iteration 5 ---------- Best LR = 0.00022756698024857996 ---------- Loss = 0.6731012780219316
Epoch [1/5], Loss: 0.6694
Epoch [2/5], Loss: 0.6362
Epoch [3/5], Loss: 0.6076
Epoch [4/5], Loss: 0.5836
Epoch [5/5], Loss: 0.5624
Accuracy: 0.7709
Precision: 0.7595
Recall: 0.7563
F1 Score: 0.7579
Confusion Matrix:
[[207  57]
 [ 58 180]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00016392470481366373 ---------- Loss = 0.7103087864816189
Iteration 2 ---------- Best LR = 0.00014753223433229735 ---------- Loss = 0.699922289699316
Iteration 3 ---------- Best LR = 0.00013277901089906762 ---------- Loss = 0.6992431450635195
Iteration 4 ---------- Best LR = 0.00011950110980916086 ---------- Loss = 0.694867080077529
Iteration 5 ---------- Best LR = 0.00010755099882824478 ---------- Loss = 0.6933993548154831
Epoch [1/5], Loss: 0.6863
Epoch [2/5], Loss: 0.6755
Epoch [3/5], Loss: 0.6597
Epoch [4/5], Loss: 0.6400
Epoch [5/5], Loss: 0.6333
Accuracy: 0.7191
Precision: 0.7263
Recall: 0.7509
F1 Score: 0.7384
Confusion Matrix:
[[162  75]
 [ 66 199]]

Average Metrics for mobilenet_v2:
Accuracy: 0.7762
Precision: 0.7690
Recall: 0.7942
F1 Score: 0.7813

--- Model with Extra Convolutional Layer ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0009576409414847134 ---------- Loss = 0.6946224123239517
Iteration 2 ---------- Best LR = 0.0008618768473362421 ---------- Loss = 0.6828402485698462
Iteration 3 ---------- Best LR = 0.0007756891626026179 ---------- Loss = 0.6759529449045658
Iteration 4 ---------- Best LR = 0.0006981202463423561 ---------- Loss = 0.6661930978298187
Iteration 5 ---------- Best LR = 0.0006283082217081206 ---------- Loss = 0.6624335683882236
Epoch [1/5], Loss: 0.6414
Epoch [2/5], Loss: 0.5898
Epoch [3/5], Loss: 0.5307
Epoch [4/5], Loss: 0.4557
Epoch [5/5], Loss: 0.3825
Accuracy: 0.8805
Precision: 0.8556
Recall: 0.9222
F1 Score: 0.8876
Confusion Matrix:
[[205  40]
 [ 20 237]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0003432285996615005 ---------- Loss = 0.6966529916971922
Iteration 2 ---------- Best LR = 0.0003089057396953505 ---------- Loss = 0.6929350346326828
Iteration 3 ---------- Best LR = 0.00027801516572581545 ---------- Loss = 0.6912781931459904
Iteration 4 ---------- Best LR = 0.00025021364915323393 ---------- Loss = 0.6883125640451908
Iteration 5 ---------- Best LR = 0.00022519228423791053 ---------- Loss = 0.6855379343032837
Epoch [1/5], Loss: 0.6765
Epoch [2/5], Loss: 0.6624
Epoch [3/5], Loss: 0.6396
Epoch [4/5], Loss: 0.6175
Epoch [5/5], Loss: 0.5951
Accuracy: 0.7231
Precision: 0.7124
Recall: 0.6975
F1 Score: 0.7049
Confusion Matrix:
[[197  67]
 [ 72 166]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.00010181838494634643 ---------- Loss = 0.6914635356515646
Iteration 2 ---------- Best LR = 9.163654645171179e-05 ---------- Loss = 0.689199659973383
Iteration 3 ---------- Best LR = 9.163654645171179e-05 ---------- Loss = 0.689199659973383
Iteration 4 ---------- Best LR = 7.422560262588654e-05 ---------- Loss = 0.6891053803265095
Iteration 5 ---------- Best LR = 6.680304236329789e-05 ---------- Loss = 0.687167489901185
Epoch [1/5], Loss: 0.6866
Epoch [2/5], Loss: 0.6826
Epoch [3/5], Loss: 0.6749
Epoch [4/5], Loss: 0.6706
Epoch [5/5], Loss: 0.6640
Accuracy: 0.7311
Precision: 0.8385
Recall: 0.6075
F1 Score: 0.7046
Confusion Matrix:
[[206  31]
 [104 161]]

Average Metrics for mobilenet_v2:
Accuracy: 0.7782
Precision: 0.8022
Recall: 0.7424
F1 Score: 0.7657

Running experiments for model: densenet121

--- Base Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to /root/.cache/torch/hub/checkpoints/densenet121-a639ec97.pth
100%|██████████| 30.8M/30.8M [00:00<00:00, 151MB/s]


Iteration 1 ---------- Best LR = 0.00010574921306512938 ---------- Loss = 0.7070404253900051
Iteration 2 ---------- Best LR = 9.517429175861645e-05 ---------- Loss = 0.7013835553079844
Iteration 3 ---------- Best LR = 8.56568625827548e-05 ---------- Loss = 0.6969037391245365
Iteration 4 ---------- Best LR = 7.709117632447932e-05 ---------- Loss = 0.6935676205903292
Iteration 5 ---------- Best LR = 6.938205869203139e-05 ---------- Loss = 0.6899612136185169
Epoch [1/5], Loss: 0.6874
Epoch [2/5], Loss: 0.6643
Epoch [3/5], Loss: 0.6444
Epoch [4/5], Loss: 0.6258
Epoch [5/5], Loss: 0.6061
Accuracy: 0.7669
Precision: 0.8431
Recall: 0.6693
F1 Score: 0.7462
Confusion Matrix:
[[213  32]
 [ 85 172]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0008490194226839852 ---------- Loss = 0.7030334193259478
Iteration 2 ---------- Best LR = 0.0007641174804155867 ---------- Loss = 0.6756698023527861
Iteration 3 ---------- Best LR = 0.000687705732374028 ---------- Loss = 0.648821335285902
Iteration 4 ---------- Best LR = 0.0006189351591366252 ---------- Loss = 0.6308884657919407
Iteration 5 ---------- Best LR = 0.0005570416432229627 ---------- Loss = 0.6143607217818499
Epoch [1/5], Loss: 0.5808
Epoch [2/5], Loss: 0.4688
Epoch [3/5], Loss: 0.3463
Epoch [4/5], Loss: 0.2592
Epoch [5/5], Loss: 0.2004
Accuracy: 0.9263
Precision: 0.9036
Recall: 0.9454
F1 Score: 0.9240
Confusion Matrix:
[[240  24]
 [ 13 225]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0006076887710532221 ---------- Loss = 0.6952377837151289
Iteration 2 ---------- Best LR = 0.0005469198939479 ---------- Loss = 0.6795173306018114
Iteration 3 ---------- Best LR = 0.00049222790455311 ---------- Loss = 0.6612170320004225
Iteration 4 ---------- Best LR = 0.000443005114097799 ---------- Loss = 0.6496544238179922
Iteration 5 ---------- Best LR = 0.00039870460268801906 ---------- Loss = 0.6344296392053366
Epoch [1/5], Loss: 0.6034
Epoch [2/5], Loss: 0.5104
Epoch [3/5], Loss: 0.4057
Epoch [4/5], Loss: 0.3240
Epoch [5/5], Loss: 0.2628
Accuracy: 0.9422
Precision: 0.9609
Recall: 0.9283
F1 Score: 0.9443
Confusion Matrix:
[[227  10]
 [ 19 246]]

Average Metrics for densenet121:
Accuracy: 0.8785
Precision: 0.9026
Recall: 0.8476
F1 Score: 0.8715

--- Fine-tuned Model ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0008090569905416364 ---------- Loss = 0.7183056697249413
Iteration 2 ---------- Best LR = 0.0007281512914874727 ---------- Loss = 0.7030003312975168
Iteration 3 ---------- Best LR = 0.0006553361623387254 ---------- Loss = 0.6876394096761942
Iteration 4 ---------- Best LR = 0.0005898025461048529 ---------- Loss = 0.6745864674448967
Iteration 5 ---------- Best LR = 0.0005308222914943676 ---------- Loss = 0.6655378099530935
Epoch [1/5], Loss: 0.6397
Epoch [2/5], Loss: 0.5691
Epoch [3/5], Loss: 0.5031
Epoch [4/5], Loss: 0.4460
Epoch [5/5], Loss: 0.3974
Accuracy: 0.9064
Precision: 0.9134
Recall: 0.9027
F1 Score: 0.9080
Confusion Matrix:
[[223  22]
 [ 25 232]]

Starting Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0007324344688268797 ---------- Loss = 0.6965902224183083
Iteration 2 ---------- Best LR = 0.0006591910219441917 ---------- Loss = 0.6819518450647593
Iteration 3 ---------- Best LR = 0.0005932719197497726 ---------- Loss = 0.666703924536705
Iteration 4 ---------- Best LR = 0.0005339447277747954 ---------- Loss = 0.6574420407414436
Iteration 5 ---------- Best LR = 0.00048055025499731585 ---------- Loss = 0.6483447831124067
Epoch [1/5], Loss: 0.6335
Epoch [2/5], Loss: 0.5667
Epoch [3/5], Loss: 0.5110
Epoch [4/5], Loss: 0.4580
Epoch [5/5], Loss: 0.4050
Accuracy: 0.8665
Precision: 0.8701
Recall: 0.8445
F1 Score: 0.8571
Confusion Matrix:
[[234  30]
 [ 37 201]]

Starting Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Iteration 1 ---------- Best LR = 0.0005408658105401537 ---------- Loss = 0.7219465002417564
Iteration 2 ---------- Best LR = 0.0004867792294861384 ---------- Loss = 0.6945496201515198
Iteration 3 ---------- Best LR = 0.00043810130653752457 ---------- Loss = 0.684732124209404
Iteration 4 ---------- Best LR = 0.00039429117588377213 ---------- Loss = 0.6791095677763224
Iteration 5 ---------- Best LR = 0.00035486205829539494 ---------- Loss = 0.670441186055541
Epoch [1/5], Loss: 0.6568
Epoch [2/5], Loss: 0.6082
Epoch [3/5], Loss: 0.5666
Epoch [4/5], Loss: 0.5273
Epoch [5/5], Loss: 0.4853
Accuracy: 0.8625
Precision: 0.9188
Recall: 0.8113
F1 Score: 0.8617
Confusion Matrix:
[[218  19]
 [ 50 215]]

Average Metrics for densenet121:
Accuracy: 0.8785
Precision: 0.9008
Recall: 0.8529
F1 Score: 0.8756

--- Model with Extra Convolutional Layer ---

Starting Fold 1


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)



An error occurred while processing model densenet121: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 1024, 7, 7]], which is output 0 of ReluBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "<ipython-input-14-4be056742512>", line 63, in run_experiments
    extra_conv_model, extra_conv_metrics = k_fold_cross_validation(
  File "<ipython-input-13-36e41784db3c>", line 22, in k_fold_cross_validation
    best_lr = simulated_annealing_lr(model, criterion, train_loader)
  File "<ipython-input-11-3db5bcef3cdc>", line 19, in simulated_annealing_lr
    loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=Inception_V3_Weights.IMAGENET1K_V1`. You can also use `weights=Inception_V3_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Iteration 1 ---------- Best LR = 0.0005565202249604948 ---------- Loss = 0.6146754613146186
Iteration 2 ---------- Best LR = 0.0005008682024644453 ---------- Loss = 0.38972865603864193
Iteration 3 ---------- Best LR = 0.00045078138221800077 ---------- Loss = 0.2801174819469452
Iteration 4 ---------- Best LR = 0.00040570324399620073 ---------- Loss = 0.21716113667935133
Iteration 5 ---------- Best LR = 0.0003651329195965807 ---------- Loss = 0.1830223232973367
Epoch [1/5], Loss: 0.2315
Epoch [2/5], Loss: 0.1360
Epoch [3/5], Loss: 0.1045
Epoch [4/5], Loss: 0.0711
Epoch [5/5], Loss: 0.0680
Accuracy: 0.9681
Precision: 0.9582
Recall: 0.9805
F1 Score: 0.9692
Confusion Matrix:
[[234  11]
 [  5 252]]

Starting Fold 2
Iteration 1 ---------- Best LR = 0.000831110617610465 ---------- Loss = 0.559144395403564
Iteration 2 ---------- Best LR = 0.0007479995558494185 ---------- Loss = 0.29919401044026017
Iteration 3 ---------- Best LR = 0.0006731996002644767 ---------- Loss = 0.18735549482516944
Itera